<?php 

$tooltip_news = 'Лента обновлений';
$tooltip_subscribe = 'Мои подписки';
$tooltip_setting = 'Мои настройки';
$tooltip_gallery = 'Моя галерея';
$tooltip_gift = 'Мои подарки';
$tooltip_information = 'Важная информация';

$avatar_change = 'Изменить аватар';

$nickname = 'Заполнить больше информации';

$choice_fate = 'выбрать судьбу';
$try = 'осталось попыток:';

$acquainted = 'Познакомится:';
$walk = 'Погулять:';
$sleepen = 'Переспать:';

 ?>