<?php 

$no_message = 'У Вас ещё нет сообщений!';

$dialog_fate = 'Диалог с судьбой';
$dialog_employee = 'Диалог с сотрудником';

$search_message = 'Найти диалог с пользователем...';

$delete_message = 'Удалить';

$message_spam = 'Сообщить о спаме';

$send_message = 'Напишите Ваше сообщение...';

$back = 'Назад';

$message_today = 'сегодня';
$message_yesterday = 'вчера';

$arr_month_abbreviation = [
  'янв',
  'фев',
  'мар',
  'апр',
  'мая',
  'июн',
  'июл',
  'авг',
  'сен',
  'окт',
  'ноя',
  'дек'
];

$arr_month = [
  'января',
  'февраля',
  'марта',
  'апреля',
  'мая',
  'июня',
  'июля',
  'августа',
  'сентября',
  'октября',
  'ноября',
  'декабря'
];

$no_message = 'Здесь будут отображаться диалоги с пользователями!';
$not_message = 'Здесь будет отображаться переписка с этим пользователем!';

$gift_message = 'Подарок';
$block_message = 'Заблокировать';
$delete_message_li = 'Удалить диалог';

$message_search = 'Поиск сообщений в диалоге...';
$message_search_calendar = 'Поиск сообщений по дате...';
$message_search_button = 'найти';

$delete_dislog = 'Удаление диалога';
$delete_dislog_2 = 'Вы действительно хотите';
$delete_dislog_3 = 'удалить';
$delete_dislog_4 = 'весь диалог с этим пользователем?';
$delete_dislog_5 = 'Отменить это действие будет';
$delete_dislog_6 = 'невозможно';

$delete_dialog_button_yes = 'удалить';
$delete_dialog_button_no = 'отменить';

 ?>
