<?php 

$change_data = 'Изменить личные данные:';
$setting_name = 'Введите Ваше имя';
$setting_nickname = 'Введите свой никнейм';

$setting_city = 'Введите Ваше место нахождения';

$change_orientation = 'Изменить ориентацию';
$heterosexual = 'Гетеросексуал';
$lesbian = 'Лесбиянка';
$gay = 'Гей';
$bi = 'Би';

$change_floor = 'Изменить пол';
$floor_man = 'Мужской';
$floor_woman = 'Женский';

$more_information = 'Заполнить больше информации';
$more_information_close = 'Скрыть блок';

$your_height = 'Ваш рост';
$your_weight = 'Ваш вес';
$eye_color = 'Цвет глаз';
$color_hair = 'Цвет волос';

$your_hobby = 'Ваше хобби';
$purpose_life = 'Цель жизни';
$religion = 'Ваша религия';


$change_password = 'Изменить пароль:';
$password_placegolder1 = 'Введите пароль';
$password_placegolder2 = 'Подтвердите пароль';

$change_language = 'Выберите язык сайта:';

$save_change = 'Сохранить изминения';

$setting_privat_policy = 'Просмотреть политику конфиденциальности';

$not_delete_page = 'Не делай этого!';

$delete_page = 'Вы можете выйти из игры,';
$delete_page_2 = 'удалить аккаунт!';

?>