<?php 
$friend = 'Друзья';
$readers = 'Читатели';
$tracked = 'Отслеживаются';

$title_blocked = 'Заблокировать';
$title_blocked_no = 'Розблокировать';
$title_subscribe = 'Подписаться';
$add_friend = 'Добавить';
$title_subscribe_no = 'Отписаться';
$delete_friend = 'Удалить';

$not_friends = 'Здесь будут отображаться Ваши друзья!';

$unsubscribe_button = 'Отписаться';

$no_subscribe_you = 'Здесь будут отображаться Ваши отслеживания!';
$no_subscribe_your = 'Здесь будут отображаться Ваши читатели!';

 ?>