<?php 

$more_information_search = 'Больше информации';
$more_information_search_close = 'Скрыть информацию';

$sm = 'Рост';
$kg = 'Вес';
$color_eyes = 'Цвет глаз';
$color_heir = 'Цвет волос';

$hobby = 'Хобби';
$purpose_life = 'Цель жизни';
$religion = 'Религия';

$not_specified = ' не указано';

$yes_fate = 'Подтвердить предложение';
$not_fate = 'Искать дальше';

$error_fate = 'На сегодня все попытки на выбор судьбы использованы!';
$error_fate_2 = 'Чтобы получить больше попыток, Вы можете их';
$error_fate_3 = 'купить!';

 ?>