 <?php
 $errors = $this->get('errors');
 echo $errors;
 if (isset($_SESSION['lang'])) {
 	$lang = $_SESSION['lang'];
 	$path = 'language/'.$lang.'/templates/authorization.phtml';
 	require($path);	

 } else {
 	require('language/ru/templates/authorization.phtml');
 	$lang = 'ru';
 }
 ?>
 <!DOCTYPE html>
 <html lang="en">
 <head>
 	<meta charset="UTF-8">
 	<title>Registration</title>
 	<link rel="shortcut icon" href="/img/icon.png" type="image/x-icon">
 	<link rel="stylesheet" href="../styles/registration.css">
 	<link rel="stylesheet" href="../styles/style.css">
 	<link rel="stylesheet" href="../styles/select.css">
 	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
 	<script type="text/javascript" src="../script/authorization.js"></script>
 </head>
 <body class="registration">
 	<?php 
 	if (!isset($_SESSION['login'])) {            
 		?>
 		<div class="registration">
 			<div class="adult">
<h3><?php echo $entrance; ?></h3>
 			</div>
 			<div class="logo_registration">
 				<img src="../img/logo1.png">
 			</div>
 			<div class="langbar">
 				<?php $redirect = 'http://' . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI']; ?>
 				<form action="<?php echo base_url .'authorization';?>" method="post">
 					<?php echo $choice_language .$language; ?>
 					<select name="language" onchange="this.form.submit()">
 						<option value="en" <?=($lang=='en')?'selected':''?>>English</option>
 						<option value="ru" <?=($lang=='ru')?'selected':''?>>Русский</option>
 						<option value="ua" <?=($lang=='ua')?'selected':''?>>Українська</option>
 					</select>         
 					<input type="hidden" name="redirect" value="<?php echo $redirect;?>">
 				</form>
 			</div>
 		</div>
 		<?php if (!isset($_GET['login']) && !isset($_GET['confidentiality_policy'])) { ?> 
 		<div class="registration_block">
 			<div class="reg_block_left">
 				<div class="reg_block_left_overlay">
 					<div class="reg_block_left_overlay_content">
 						<h2><?php echo $welcome; ?></h2>
 						<br>
 						<p><?php echo $visited; ?>
 							<br><br>
 							<?php echo $goodluck; ?>
 						</p>
 						<div class="reg_block_left_footer">
 							<p><?php echo date('Y'); ?> ©Randomly - production of Bulavin brothers.</p>
 						</div>
 					</div>	
 				</div>
 			</div>
 			<div class="reg_block_right">
 				<?php $select = ($_POST['sex']);
 				$selected[$select]='selected'; ?>
 				<h3><?php echo $poll; ?></h3>
 				<br>
 				<p><?php echo $question1; ?></p>
 				<form action="<?php echo base_url .'authorization';?>" method="post">
 					<select name="sex" class="turnintodropdown" required>
 						<option value=""><?php echo $question1_2; ?></option>
 						<option value="1" <?=($_POST['sex']=='1')?'selected':''?>><?php echo $question1_3; ?></option>
 						<option value="0" <?=($_POST['sex']=='0')?'selected':''?>><?php echo $question1_4; ?></option>
 					</select>
 					<br><br>
 					<p><?php echo $question2; ?></p>
 					<input type="text" name="name" placeholder="<?php echo $question2_2; ?>" value="<?php echo @$_POST['name'] ?>" required>
 					<br>
 					<?php 
 					if (!empty($errors)) {?>
 					<div id="errore_email" data-description="<?php echo $error_email; ?>"> 						
 					</div>
 					<?php } ?>
 					<input type="email" name="email" placeholder="<?php echo $question2_3; ?>" value="<?php echo @$_POST['email'] ?>" required>
 					<br>
 					<input class="left_password valid_pass" type="password" name="password" placeholder="<?php echo $question2_4; ?>" minlength="6" required>
 					
 					<input class="right_password valid_pass" type="password" name="password_confirm" placeholder="<?php echo $question2_5; ?>" minlength="6" required>
 					<br><br><br>
 					<p><?php echo $question3; ?></p>
 					<?php if (!empty($errors)) {?>
 					<div id="errore_email" data-description="<?php echo $error_date; ?>">
 					</div>
 					<?php } ?>
 					<input type="date" name='date_birth' value="<?php echo @$_POST['date_birth'] ?>" required/>
 					<br><br>
 					<p><?php echo $question4; ?></p>

 					<select name="city" class="turnintodropdown" required>
 						<option value=""><?php echo $question4_2; ?></option>
 						<option value="Kyiv"  <?=($_POST['city']=='Kyiv')?'selected':''?>><?php echo $question4_3; ?></option>
 						<option value="Lviv"  <?=($_POST['city']=='Lviv')?'selected':''?>><?php echo $question4_4; ?></option>
 						<option value="Rivne"  <?=($_POST['city']=='Rivne')?'selected':''?>><?php echo $question4_5; ?></option>
 					</select> 
 					<br><br>
 					<p><?php echo $orientation; ?></p>
 					<select name="orientation" class="turnintodropdown" required>
 						<option value="">Виберите ориентацию</option>
 						<option value="heterosexual"  <?=($_POST['orientation']=='heterosexual')?'selected':''?>>Гетеросексулал</option>
 						<option value="lesbian"  <?=($_POST['orientation']=='lesbian')?'selected':''?>>Лесбианка</option>
 						<option value="gay"  <?=($_POST['orientation']=='gay')?'selected':''?>>Гей</option>
 						<option value="beesexual"  <?=($_POST['orientation']=='beesexual')?'selected':''?>>Бисексуал</option>
 					</select>
 					<br><br>
 					<input type="submit" name='register' value="<?php echo $button_register; ?>">

 					<p class="privat_policy">
 						<input type="checkbox" name="agreement" id="cb1" value="YES" /> 
 						<label for="cb1"><?php echo $privat_policy_register; ?>
 							<a href="<?php echo base_url .'authorization?confidentiality_policy';?>">
 								<?php echo $privat_policy_register_2; ?>
 							</a>
 						</label>
 					</p>
 				</form>
 				<span><a href="<?php echo base_url .'authorization?login';?>"><?php echo $login_account; ?></a></span>
 			</div>
 		</div>

 		<?php } 
 		else { 
 			if (isset($_GET['login'])) { ?>
 			<div class="login_block">
 				<div class="log_block_left">
 					<div class="reg_block_left_overlay">
 						<div class="log_block_left_overlay_content">
 							<h2><?php echo $welcome_login; ?></h2>
 							<br>
 							<p><?php echo $visited_login; ?>
 								<br><br>
 								<?php echo $goodluck_login; ?>
 							</p>

 							<br>
 							<br>
 							<form action="<?php echo base_url .'authorization?login';?>" method='post'>
 								<div id="errore_email" data-description="<?php echo $error_email_login; ?>">
 								</div>
 								<input class="input_login" type="email" name="email_login" placeholder="<?php echo $email_login; ?>" required>
 								<div id="errore_email" data-description="<?php echo $error_password_login; ?>"></div>
 								<input class="input_password" type="password" name="password_login" placeholder="<?php echo $password_login; ?>" required>
 								<br><br>
 								<input type="submit" name='login' value="<?php echo $button_login; ?>">
 							</form>
 							<span class="logut_span"><a href="<?php echo base_url .'authorization?login';?>"><?php echo $no_login; ?></a></span>
 							<div class="log_footer">

 								<p>©Randomly - Design by BULYK | Code by BULAVA</p>
 							</div>
 						</div>	
 					</div>
 				</div>

 			</div>
 		</div>
 		<?php }
 		if (isset($_GET['confidentiality_policy'])) {?>
 		<div class="content_resize">
 			<div class="center_block_content">
 				<h4>Вводя свои персональные данные и нажимая на кнопку "зарегистрироватся", Вы дали согласие на обработку своих персональных данных.</h4>
 				<br>
 				<h3>Политика в отношении обработки персональных данных.</h3>
 				<br>
 				<ul>
 					<li><span>1. Общие положения</span>
 						<br><br>
 						<p>Настоящая политика обработки персональных данных составлена в соответствии с требованиями Федерального закона от 27.07.2006. №152-ФЗ «О персональных данных» и определяет порядок обработки персональных данных и меры по обеспечению безопасности персональных данных OOO «Randomly» (далее – Оператор).
 							Оператор ставит своей важнейшей целью и условием осуществления своей деятельности соблюдение прав и свобод человека и гражданина при обработке его персональных данных, в том числе защиты прав на неприкосновенность частной жизни, личную и семейную тайну.
 							Настоящая политика Оператора в отношении обработки персональных данных (далее – Политика) применяется ко всей информации, которую Оператор может получить о посетителях веб-сайта http://randomly.org.
 							<br>
 							<br>
 							Использование Пользователем сайта означает согласие с настоящей Политикой конфиденциальности и условиями обработки персональных данных Пользователя.
 							<br>
 							<br>	
 							В случае несогласия с условиями Политики конфиденциальности Пользователь должен прекратить использование сайта.
 							<br>
 							<br>	
 							Настоящая Политика конфиденциальности применяется только к данному сайту. Администрация сайта не контролирует и не несет ответственность за сайты третьих лиц, на которые Пользователь может перейти по ссылкам, доступным на данном сайте.
 							<br>
 							<br>	
 							Администрация сайта не проверяет достоверность персональных данных, предоставляемых Пользователем сайта.	
 						</p>
 					</li>
 					<br><br>
 					<li>
 						<span>2. Основные понятия, используемые в Политике.</span>
 						<br><br>
 						<p>Автоматизированная обработка персональных данных – обработка персональных данных с помощью средств вычислительной техники;
 							Блокирование персональных данных – временное прекращение обработки персональных данных (за исключением случаев, если обработка необходима для уточнения персональных данных);
 							Веб-сайт – совокупность графических и информационных материалов, а также программ для ЭВМ и баз данных, обеспечивающих их доступность в сети интернет по сетевому адресу http://randomly.org;
 							<br>
 							Информационная система персональных данных — совокупность содержащихся в базах данных персональных данных, и обеспечивающих их обработку информационных технологий и технических средств;
 							<br>
 							Обезличивание персональных данных — действия, в результате которых невозможно определить без использования дополнительной информации принадлежность персональных данных конкретному Пользователю или иному субъекту персональных данных;
 							<br>
 							Обработка персональных данных – любое действие (операция) или совокупность действий (операций), совершаемых с использованием средств автоматизации или без использования таких средств с персональными данными, включая сбор, запись, систематизацию, накопление, хранение, уточнение (обновление, изменение), извлечение, использование, передачу (распространение, предоставление, доступ), обезличивание, блокирование, удаление, уничтожение персональных данных;
 							Оператор – государственный орган, муниципальный орган, юридическое или физическое лицо, самостоятельно или совместно с другими лицами организующие и (или) осуществляющие обработку персональных данных, а также определяющие цели обработки персональных данных, состав персональных данных, подлежащих обработке, действия (операции), совершаемые с персональными данными;
 							<br>
 							Персональные данные – любая информация, относящаяся прямо или косвенно к определенному или определяемому Пользователю веб-сайта http://randomly.org;
 							Пользователь – любой посетитель веб-сайта http://randomly.org;
 							<br>
 							Предоставление персональных данных – действия, направленные на раскрытие персональных данных определенному лицу или определенному кругу лиц;
 							<br>
 							Распространение персональных данных – любые действия, направленные на раскрытие персональных данных неопределенному кругу лиц (передача персональных данных) или на ознакомление с персональными данными неограниченного круга лиц, в том числе обнародование персональных данных в средствах массовой информации, размещение в информационно-телекоммуникационных сетях или предоставление доступа к персональным данным каким-либо иным способом;
 							Трансграничная передача персональных данных – передача персональных данных на территорию иностранного государства органу власти иностранного государства, иностранному физическому или иностранному юридическому лицу;
 							<br>
 							Уничтожение персональных данных – любые действия, в результате которых персональные данные уничтожаются безвозвратно с невозможностью дальнейшего восстановления содержания персональных данных в информационной системе персональных данных и (или) результате которых уничтожаются материальные носители персональных данных.
 						</p>
 					</li>
 					<br><br>
 					<li>
 						<span>3. Оператор может обрабатывать следующие персональные данные Пользователя</span>
 						<br><br>
 						<p>Имя;
 							<br><br>
 							Электронный адрес;
 							<br><br>
 							Год, месяц, дата и место рождения;
 							<br><br>
 							Фотографии;
 							<br><br>
 							Также на сайте происходит сбор и обработка обезличенных данных о посетителях (в т.ч. файлов «cookie») с помощью сервисов интернет-статистики (Яндекс Метрика и Гугл Аналитика и других).
 						Вышеперечисленные данные далее по тексту Политики объединены общим понятием Персональные данные.</p>
 					</li>
 					<br><br>
 					<li>
 						<span>4. Цели обработки персональных данных.</span>
 						<br><br>
 						<p>
 							Цель обработки персональных данных Пользователя — предоставление доступа Пользователю к сервисам, информации и/или материалам, содержащимся на веб-сайте.
 							Также Оператор имеет право направлять Пользователю уведомления о новых продуктах и услугах, специальных предложениях и различных событиях. Пользователь всегда может отказаться от получения информационных сообщений, направив Оператору письмо на адрес электронной почты randomly@gmail.com с пометкой «Отказ от уведомлениях о новых продуктах и услугах и специальных предложениях».
 							Обезличенные данные Пользователей, собираемые с помощью сервисов интернет-статистики, служат для сбора информации о действиях Пользователей на сайте, улучшения качества сайта и его содержания.
 						</p>
 					</li>
 					<br><br>
 					<li>
 						<span>5. Правовые основания обработки персональных данных.</span>
 						<br><br>
 						<p>
 							Оператор обрабатывает персональные данные Пользователя только в случае их заполнения и/или отправки Пользователем самостоятельно через специальные формы, расположенные на сайте http://randomly.org. Заполняя соответствующие формы и/или отправляя свои персональные данные Оператору, Пользователь выражает свое согласие с данной Политикой.
 							Оператор обрабатывает обезличенные данные о Пользователе в случае, если это разрешено в настройках браузера Пользователя (включено сохранение файлов «cookie» и использование технологии JavaScript).
 						</p>

 					</li>
 					<br><br>
 					<li>
 						<span>6. Порядок сбора, хранения, передачи и других видов обработки персональных данных.</span>
 						<br><br>
 						<p>
 							Безопасность персональных данных, которые обрабатываются Оператором, обеспечивается путем реализации правовых, организационных и технических мер, необходимых для выполнения в полном объеме требований действующего законодательства в области защиты персональных данных.
 							Оператор обеспечивает сохранность персональных данных и принимает все возможные меры, исключающие доступ к персональным данным неуполномоченных лиц.
 							Персональные данные Пользователя никогда, ни при каких условиях не будут переданы третьим лицам, за исключением случаев, связанных с исполнением действующего законодательства.
 							В случае выявления неточностей в персональных данных, Пользователь может актуализировать их самостоятельно, путем направления Оператору уведомление на адрес электронной почты Оператора randomly@gmail.com с пометкой «Актуализация персональных данных».
 							Срок обработки персональных данных является неограниченным. Пользователь может в любой момент отозвать свое согласие на обработку персональных данных, направив Оператору уведомление посредством электронной почты на электронный адрес Оператора randomly@gmail.com с пометкой «Отзыв согласия на обработку персональных данных».
 						</p>

 					</li>
 					<br><br>
 					<li>

 						<span>7. Трансграничная передача персональных данных</span>
 						<br><br>
 						<p>
 							Оператор до начала осуществления трансграничной передачи персональных данных обязан убедиться в том, что иностранным государством, на территорию которого предполагается осуществлять передачу персональных данных, обеспечивается надежная защита прав субъектов персональных данных.
 							Трансграничная передача персональных данных на территории иностранных государств, не отвечающих вышеуказанным требованиям, может осуществляться только в случае наличия согласия в письменной форме субъекта персональных данных на трансграничную передачу его персональных данных и/или исполнения договора, стороной которого является субъект персональных данных.
 						</p>

 					</li>
 					<br><br>
 					<li>
 						<span>8. Заключительные положения</span>
 						<br><br>
 						<p>
 							Пользователь может получить любые разъяснения по интересующим вопросам, касающимся обработки его персональных данных, обратившись к Оператору с помощью электронной почты randomly@gmail.com.
 							В данном документе будут отражены любые изменения политики обработки персональных данных Оператором.
 						</p>

 					</li>
 					<br>
 					<br>
 					<li>
 						<span>9. Дополнительные условия</span>
 						<br>	
 						<br>
 						<p>- Администрация сайта вправе вносить изменения в настоящую Политику конфиденциальности без согласия Пользователя.
 							<br><br>		
 						- Новая Политика конфиденциальности вступает в силу с момента ее размещения на Сайте, если иное не предусмотрено новой редакцией Политики конфиденциальности.	</p>	

 					</li>
 				</ul>
 			</div>
 		</div>

 		<?php } 
 	}?>
 	<?php }
 	else {
 		header("Location: /");
 	} ?>
 </body>
 </html>

