<?php 
$row_user = $this->get('row_user');
if (isset($row_user['language'])) {
	$lang = $row_user['language'];
	$path = 'language/'.$lang.'/templates/news.phtml';
	require($path);	

} else {
	require_once('language/ru/templates/news.phtml');
}
?>
<div class="right_block">
	<div class="search_information">
		<a>
			<i class="fas fa-search"></i>	
		</a>
		<input type="search" placeholder="<?php echo $search_post; ?>" autocomplete="off" />
	</div>
	<div id="news_users">	

	</div>
	<script>
		news_users();
		// setInterval(news_users,3000);
	</script>
</div>

