<?php 

$tooltip_news = 'Стрічка оновлень';
$tooltip_subscribe = 'Мої підписки';
$tooltip_setting = 'Мої налаштування';
$tooltip_gallery = 'Моя галерея';
$tooltip_gift = 'Мої подарунки';
$tooltip_information = 'Важлива інформація';

$avatar_change = 'Змінити аватарку';

$nickname = 'Заповнити більше інформації';

$choice_fate = 'вибрати долю';
$try = 'залишилося спроб:';

$acquainted = 'Познайомитися:';
$walk = 'Погуляти:';
$sleepen = 'Переспати:';

 ?>