<?php 
$no_message = 'У Вас ще немає повідомлень!';

$dialog_fate = 'Діалог з долею';
$dialog_employee = 'Діалог з співробітником';

$search_message = 'Знайти діалог з користувачем...';

$delete_message = 'Видалити';

$message_spam = 'Повідомити про спам';

$send_message = 'Напишіть Ваше повідомлення...';

$back = 'Назад';

$message_today = 'сьогодні';
$message_yesterday = 'вчора';

$arr_month_abbreviation = [
  'січ',
  'лют',
  'бер',
  'кві',
  'тра',
  'чер',
  'лип',
  'сер',
  'вер',
  'жов',
  'лис',
  'гру'
];

$arr_month = [
  'січня',
  'лютого',
  'березня',
  'квітня',
  'травня',
  'червня',
  'липня',
  'серпня',
  'вересня',
  'жовтня',
  'листопада',
  'грудня'
];

$no_message = 'Тут будуть відображатися діалоги з користувачами!';
$not_message = 'Тут буде відображатися листування з цим користувачем!';

$gift_message = 'Подарунок';
$block_message = 'Заблокувати';
$delete_message_li = 'Видалити діалог';

$message_search = 'Пошук повідомлень в діалозі...';
$message_search_calendar = 'Пошук повідомлень по даті...';
$message_search_button = 'знайти';

$delete_dislog = 'Видалення діалога';
$delete_dislog_2 = 'Ви дійсно хочете';
$delete_dislog_3 = 'видалити';
$delete_dislog_4 = 'весь діалог з цим користувачем?';
$delete_dislog_5 = 'Скасувати цю дію буде';
$delete_dislog_6 = 'неможливо';

$delete_dialog_button_yes = 'видалити';
$delete_dialog_button_no = 'скасувати';


 ?>
