<?php 

$change_data = 'Змінити особисті дані:';
$setting_name = "Введіть Ваше і'мя";
$setting_nickname = 'Введіть свій нікнейм';

$setting_city = 'Введіть Ваше місце знаходження';

$change_orientation = 'Змінити орієнтацію';
$heterosexual = 'Гетеросексуал';
$lesbian = 'Лесбіянка';
$gay = 'Гей';
$bi = 'Бі';

$change_floor = 'Змінити стать';
$floor_man = 'Чоловіча';
$floor_woman = 'Жіноча';

$more_information = 'Заповнити більше інформації';
$more_information_close = 'Приховати блок';

$your_height = 'Ваш зріст';
$your_weight = 'Ваша вага';
$eye_color = 'Колір очей';
$color_hair = 'Колір волосся';

$your_hobby = 'Ваше хобі';
$purpose_life = 'Ціль життя';
$religion = 'Ваша релігія';

$change_password = 'Змінити пароль:';
$password_placegolder1 = 'Введіть новий пароль';
$password_placegolder2 = 'Підтвердіть пароль';

$change_language = 'Виберіть мову сайта:';

$save_change = 'Зберегти зміни';

$setting_privat_policy = 'Переглянути політику конфіденційності';

$not_delete_page = 'Не роби це!';

$delete_page = 'Ви можете вийти з гри,';
$delete_page_2 = 'видалити аккаунт!';

?>