<?php 
$friend = 'Друзі';
$readers = 'Читачі';
$tracked = 'Відстежуються';

$title_blocked = 'Заблокувати';
$title_blocked_no = 'Розблоквати';
$title_subscribe = 'Підписатися';
$add_friend = 'Добавити';
$title_subscribe_no = 'Відписатися';
$delete_friend = 'Видалити';

$not_friends = 'Тут будуть відображатися Ваші друзі!';

$unsubscribe_button = 'Відписатися';

$no_subscribe_you = 'Тут будуть відображатися Ваші відстеження!';
$no_subscribe_your = 'Тут будуть відображатися Ваші читачі!';

 ?>