<?php 

$more_information_search = 'Більше інформації';
$more_information_search_close = 'Приховати інформацію';

$sm = 'Зріст';
$kg = 'Вага';
$color_eyes = 'Колір очей';
$color_heir = 'Колір волосся';

$hobby = 'Хобі';
$purpose_life = 'Ціль життя';
$religion = 'Релігія';

$not_specified = ' не вказано';

$yes_fate = 'Підтвердити пропозицію';
$not_fate = 'Шукати далі';

$error_fate = 'На сьогодні всі спроби на вибір долі використані!';
$error_fate_2 = 'Щоб отримати більше спроб, Ви можете їх';
$error_fate_3 = 'придбати!';
 ?>